# Validation config for Pb MTP potential

element: Pb

lammps_cmd: /home/saitto/active-learning-ML-potential-KTH/codes/mylammps/src/lmp_mpi
classical_lammps_cmd: /home/saitto/active-learning-ML-potential-KTH/codes/mylammps/src/lmp_mpi
mpi_command: mpirun
mpi_np: 8

structures:
  fcc:
    data_file: reference_structures/fcc_Pb.lammps

eos:
  enabled: false
  n_points: 25
  scale_min: 0.85
  scale_max: 1.15

elastic:
  enabled: false
  delta: 0.005

melting:
  enabled: false
  T_start: 595
  T_end: 605
  T_step: 5
  supercell_repeat: 5
  n_equil: 5000
  n_prod: 20000
  dt: 0.004

thexp:
  enabled: false
  temperatures: [100, 200, 300, 400, 500]
  n_equil: 5000
  n_prod: 10000
  dt: 0.002

vacancy:
  enabled: false
  supercell_repeat: 3

rdf:
  enabled: true
  temperature: 700
  supercell_repeat: 3
  n_equil: 5000
  n_prod: 20000

classical_references:
  - label: Lee2003-MEAM
    enabled: true
    pair_style: "meam"
    pair_coeff: "* * /home/saitto/mlip_pipeline_v1/reference_potentials/library.meam Pb /home/saitto/mlip_pipeline_v1/reference_potentials/Pb.meam Pb"

  - label: Zhou2004-EAM
    enabled: true
    pair_style: "eam/alloy"
    pair_coeff: "* * reference_potentials/Pb_Zhou04.eam.alloy Pb"